services:
  db-users:
    image: postgres:15-alpine
    container_name: ilia-db-users
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db-users-data:/var/lib/postgresql/data
    networks:
      - ilia-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  db-transactions:
    image: postgres:15-alpine
    container_name: ilia-db-transactions
    environment:
      POSTGRES_DB: transactions_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - db-transactions-data:/var/lib/postgresql/data
    networks:
      - ilia-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  ilia-network:
    driver: bridge

volumes:
  db-users-data:
  db-transactions-data:
