name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies - ms-users
      working-directory: packages/ms-users
      run: npm install

    - name: Generate Prisma Client - ms-users
      working-directory: packages/ms-users
      run: npx prisma generate

    - name: Install dependencies - ms-transactions
      working-directory: packages/ms-transactions
      run: npm install

    - name: Generate Prisma Client - ms-transactions
      working-directory: packages/ms-transactions
      run: npx prisma generate

    - name: Lint - ms-users
      working-directory: packages/ms-users
      run: npm run lint

    - name: Lint - ms-transactions
      working-directory: packages/ms-transactions
      run: npm run lint

    - name: Test - ms-users
      working-directory: packages/ms-users
      run: npm test

    - name: Test - ms-transactions
      working-directory: packages/ms-transactions
      run: npm test

    - name: Build - ms-users
      working-directory: packages/ms-users
      run: npm run build

    - name: Build - ms-transactions
      working-directory: packages/ms-transactions
      run: npm run build
